### ISSUE TITLE
The car's off peak charging setting automatically disables when using this plugin.

### ISSUE THREAD

**Issue by joopmartens** [PierreLevres/BlUVO#8]
Hi.
First, thanks for this plugin! it's really great to integrate the car with Domoticz.
very nice work!

I'm using BIUVO as a plugin in Domoticz and it works great although I have one issue:
When the plugin is enabled it seems to disable the setting of my car to only charge in off peak hours when the car is at home.

I have disabled the plugin in Domoticz and now the car keeps charging only in off peak hours. (After that I re-enabled the setting manually in the car).

Any idea why this is happening and if this can be avoided so that the off peak charging setting remains active?

Thanks in advance for your support.

**Comment by PierreLevres** [comment]
The plugin does not send any api-calls to the car regarding charging during off-peak hours or charge schedules.
How does your UVO/Bluelink app behave?

**Comment by joopmartens** [comment]
The only issue that I had with the UVO app while I had the Domoticz plugin enabled was that it often provided an error that it was not able to communicate with the car that also has been solved since I disabled the plugin.

But in case the plugin does not send any api-calls to the car regarding charging during off-peak hours or charge schedules I'm also not sure if my issue was caused by the plugin at all.

I'm going to re-enable the plugin and try to get more detailed information about the issue and if I can find out if it is related to this plugin or not.

**Comment by PierreLevres** [comment]
Feel free to create a copy/fork for the plugin. I switched from Domoticz to Homeassistant, so wont maintain plugin anymore.. I will be maintaining the api-wrapper lib however.

**Comment by JanJaapKo** [comment]
Hi @PierreLevres ,

I experience with this plugin that my Hyundai Kona does not want to start charging on a public charger (charger and vehicle report that charging is completed while the battery level is not even near 100%). When I disable it in Domoticz, all is fine. I do not have this problem at home, but there I use the 230 V cable so not sure if it is the public charging or the 11 kW charger. Anyway, it sounds a bit related to the problem reported by @joopmartens .

You mentioned here switching to HomeAssistant. Can you point me to the plugin (or what it is called in HA) that you are using? Then I can ty to fix this part in Domoticz as well.

**Comment by PierreLevres** [comment]
i cannot reproduce the errors you mention about charging, especially since the plugin-code is just about reading from the car.

at the moment in homeassistant i am using a node-red plugin called node-red-contrib-bluelinky and feeding into to HA via MQTT
the node-red plugin and related interface code is maintained by a larger group of people.

apparently in home assistant there is also a custom python plugin, to be found here: https://github.com/fuatakgun/kia_uvo
for hyundai it takes changing a few parameters, which you can see also in the domoticz plugin code, in https://github.com/PierreLevres/BlUVO/blob/master/bluvo_lib.py
i havent tried it yet…
